### ISSUE TITLE
Video Corruption Hardware Version 1 Firmware Version .202

### ISSUE THREAD

**Issue by c64manguy** [frntc/SIDKick-pico#54]
I still have the bug with the NTSC C64 where the Sidkick menu becomes corrupted and the sound doesn't work when you switch to 6581. See the attached image. In the menu, it still says FW .20. Im wondering if the .202 release wasn't correctly updated for the V1 PCB...
![Sidkick_V1_FW202_Menu_1](https://github.com/frntc/SIDKick-pico/assets/125417812/7bf9eba5-5581-4f6d-9905-fc45b9270072)

**Comment by frntc** [comment]
If you flash the firmware and never launch the config tool, does it play audio when you start some SID-tune?

**Comment by c64manguy** [comment]
Yeah. It works normally if I don't access the menu. It also works normally if I do access the menu but don't change the sid type to 6581.

**Comment by ziggystar12** [comment]
Same here, I accidentally loaded the V2 hardware firmware, and it did work actually, wondering same thing when I loaded the proper v1 firmware.

**Comment by frntc** [comment]
I'll have a look, I only have one NTSC machine to test with, plz be patient.

**Comment by jojessf** [comment]
I'm not being impatient, but came to offer some info in case it's helpful!

Similar issue.  Not being impatient - I'm sure everyone really really appreciates the awesome project!  I can get mine to work if I use the v014 firmware.  :3 

Testing via V1 PCB.  .202 firmware.  NTSC C64.

[1] /Any/ adjustment to sid0's type, or to sid1, seems to result in a complete loss of sound ... until I re-flash the firmware [ and run on defaults ].  Loading into the launcher itself does not appear to cause any issues - I can SYS54301, load sidplay, and play SIDs just fine on sid0=8580.  Until I touch the settings, then it's zero-audio until reboot.  I went and soldered some pins to a [prebuilt] PCM5102A with the hopes that it was just a bug with PCM output, but alas - it seems to affect both.  

Tried flashing with SKpico2_DAC.uf2, SKpico2_DAC_PWM.uf2, & SKpico2_PWM.uf2 - same results.

[2] tested against the .20 firmware - SKpico2_DAC_PWM.uf2.  Sound on both PCM & DAC ... until I mess with the settings.

[3] Tested with the v014 firmware - and I was able to run six channels [ sid[01] ~ 8580 ] via SidWiz2...!  So that works!  Shame that I can't use sid1 without sacrificing the [heccin _**sicc**_ PRG launcher] ... yet?  But at least I can fool around writin' for two sids, now! :3c 

( This project is so hecking cool, and I really really appreciate your work, frntc!!!  <3 )

PS:  In my case the graphical glitch on the ( .20x ) launcher ( following changes to either sid ) is a bit different from OP.
![image](https://github.com/frntc/SIDKick-pico/assets/60476425/fb18c67e-14f4-4295-99df-894a37882436)

**Comment by frntc** [comment]
I think I know where the problem is, just not 100% sure why it does not appear on my NTSC machine (but I only have one native NTSC-C64, and no two Commodore machines are equal). It's a 0.2x-thing, which I wanted to fix it together with something else.

**Comment by Freeluke74** [comment]
HI fmtc, 
I have same problem of glitch with my sidkick pico 0.2. I noticed that the problem is present on FW ver 0.201 and 0.202. With 0.200 is OK. I tested it in 2 PAL machines a C64 breadborad with PCB 250407 and have graphic glitchs on configuration menu and of i modify the items i can't notice difference example if i modify volume of SID 1 when play the integrated music no effect on volume. In a C64C CR instead i can't open configuration menu via SYS 54301 or SYS54333!
Instead using ver 0.200 of fw i can use sidkick pico on both board and the menu is OK, if I change volume when plaing the intehgrated music this have effect.
I used a Raspberry clone (https://it.aliexpress.com/item/1005003371056277.html?spm=a2g0o.order_list.order_list_main.136.a0c33696GeNUBL&gatewayAdapt=glo2ita)  the black version with RGB LED and 16M

**Comment by frntc** [comment]
Have you guys played with the timings? They can be set using SKpicopatch.exe -- maybe increase/decrease both by 2 (default values are shown by SKpicopatch).

If this doesn't help: I can't reproduce the problem here, but if someone with reproduceable problems volunteers to test, then I can send some testing firmwares (you find my mail address in any source code file)

**Comment by c64manguy** [comment]
I will play around with the timing settings tomorrow or Monday. As for testing, I'd be more than happy to test. I have several 250407s, a couple 250425s, a 250466, a c128, and a 326298 rev a. I'll email you tomorrow so you can send the test firmware. 

Thanks again! Great project and great work!

**Comment by Freeluke74** [comment]
> Have you guys played with the timings? They can be set using SKpicopatch.exe -- maybe increase/decrease both by 2 (default values are shown by SKpicopatch).
> 
> If this doesn't help: I can't reproduce the problem here, but if someone with reproduceable problems volunteers to test, then I can send some testing firmwares (you find my mail address in any source code file)

I will make some tests modifying the timings as you suggest

**Comment by Freeluke74** [comment]
Ok, I tested 4 combination of different timings with firmware 0.202 board 250407 PAL

phi2 13  bus 11    -  same situation, glitch on config screen and no effect on modified parameter (ex SID 1 volume)
phi2 15  bus 9     -   same situation, glitch on config screen and no effect on modified parameter (ex SID 1 volume)
phi2 17  bus 11    -  same situation, glitch on config screen and no effect on modified parameter (ex SID 1 volume)  No music with P key
phi2 15 bus 13   -   same situation, glitch on config screen and no effect on modified parameter (ex SID 1 volume)

You confirm that i can modify phi and bus with SKpicopatch.exe also if i not add any PRG ?

Have you any combination of timings to suggest?

**Comment by frntc** [comment]
Thanks, no there are no specific timing suggestions (other than the default values, which seem to work on 99% of the machines). Write me a mail then I'll prepare some test firmwares to nail this problem down.

**Comment by Freeluke74** [comment]
> Thanks, no there are no specific timing suggestions (other than the default values, which seem to work on 99% of the machines). Write me a mail then I'll prepare some test firmwares to nail this problem down.

I sent you an email

**Comment by frntc** [comment]
So far we were able to solve all these corruption problems by adjusting the timings. Special thanks to @c64manguy for lots of testing! Hopefully the diagnostic test in the config tool points to timing issues more prominently now :-)

**Comment by Freeluke74** [comment]
Hi, I tried to set a lot of combination of timings but the problem whasn't resolved on my 2 PAL PCB 250407 and 250469. Have @c64manguy used pal machines? Wich timigs had used to view the configuration menu without glitch? I used also new firmware 0.21 forcing timigs with SKpicotiming.prg but no solution to problem.

**Comment by frntc** [comment]
He used timings as low as 7/5 or so. If you still have glitches and the config tool doesn't show diagnostic warnings, the problem might also be somewhere else (e.g. flash of the Pico... I could prepare a test version, which does nothing else but testing for this problem...but maybe you have another Pico to test?)

**Comment by Freeluke74** [comment]
I tested also 7 / 5  but no difference. I modified phi2 and bus - i'm waiting for another pico to test. now i have a pico clone with 16M and RGB led. Unfortunately i have soldered pico on sidekick PCB so i must unsolder it to test other pico

**Comment by c64manguy** [comment]
The timings that worked best for me when I had issues were 13/9 and 11/8. If you set them in the C64 with skpicotiming.prg, remember, the smaller number comes first.

**Comment by Freeluke74** [comment]
nothing to do, tested 13/9 and 11/8 but same problem. I don't understand why in firmware 0.20 is all OK but from 0.201 above i have glitches on 2 different PCB and changing timings have poor effect. What is changed from that firmware?

**Comment by frntc** [comment]
Lots of things have changed, but nothing that should do that. Have you sent me a mail previously? (got lost matching github names and mails) If you do so, I could prepare a special version for testing something.

**Comment by Freeluke74** [comment]
Yes, i sent an email 3 weeks ago.

**Comment by Freeluke74** [comment]
have you received my email ?

**Comment by Freeluke74** [comment]
> I tested also 7 / 5 but no difference. I modified phi2 and bus - i'm waiting for another pico to test. now i have a pico clone with 16M and RGB led. Unfortunately i have soldered pico on sidekick PCB so i must unsolder it to test other pico

Good news! @frntc  yesterday i desoldered the rasppico clone 16MB with RGB and soldered a RaspPico original and now all is OK, i used without problem last firmware 0.21 on assy 240407.  I will make other test on other assy and will try other raspclone

**Comment by Freeluke74** [comment]
But the mystery continues... I also tried two other Raspico clones, one black with RGB LED at 16M and one purple with 4MB.
The black one 16MB RGB has the same defect as the first one I tried, that is, with firmware 0.20 it works but with 0.21 it gives messed up images.
With the purple one I can't access the configuration menu with the SYS543... it cleans the screen with ready and a flashing cursor. I also tried this one with firmware 0.20 and 0.21 but in both cases it doesn't work.
So the incompatibilities seem to be present only with the clones, not with the originals.
Why?

**Comment by Freeluke74** [comment]
OK, the purple is out, I didn't see the difference in pinout. 
But the two black ones with RGB leds, bought from two different sellers, have the same glitch problem with firmware over 0.20. I checked for faulty soldering but everything seems OK. I don't understand where the error could be.

**Comment by Freeluke74** [comment]
> Do you have any aftermarket chips( replacement roms, cpu, pla, vic2, etc...) in your machines? When I was doing my testing, I had significantly more timing issues in my machines with replacement ROMs.

Only PLA with 2 GAL 20v8 on assy 250407, but i tested also a 250469 all original. In both of them ROM are original

**Comment by Nephrite-FM** [comment]
I'm also having issues.  The Config menu fails to load at all on a 250407, but works perfectly on my C64C shortboard in either PAL or NTSC Mode.  This is with an official Raspberry Pi PICO board.

We are also having problems on he 250407 board with other devices, perhaps it is because we had to replace the KERNAL rom and timings are being thrown off...

**Comment by frntc** [comment]
@Nephrite-FM then it's probably really something else. What other devices fail to work?

**Comment by Nephrite-FM** [comment]
> @Nephrite-FM then it's probably really something else. What other devices fail to work?

We have a Commodore4Ever wifi modem that runs at 1200 baud on the user port that gets scrambled text.  The system also fails the 586220 tests with an intermittent fault bouncing between the User port, CIA chips, etc., and sometimes freezes on the noise part of the SID test.  These tests fail despite swapping out CIAs, CPUs and Components from my C64C system which passed thousands of 586220 test cycles.  The CIA and CPU test fine in my working C64 system.  We even transferred things over from the 250407 into a new 250466 PCB, replacing the clock circuit entirely, yet it still garbles text from the modem and still doesn't get us into the SidKick menu (SYS54301).  The sidkick at least generates sound when plugged in to the bad board, though.  

I am suspecting, because the new Kernal Rom sits on a 2764 to 2364 interposer board and is an ATMEL 28C64B, and the original Character and Basic ROMs are the original mask roms that the timing is screwy.  We don't have a Spare Kernal Mask ROM IC to test (my C64C is a short oard).
